### ISSUE TITLE
Breaking changes between versions

### ISSUE THREAD

**Issue by EddieOne** [thenativeweb/crypto2#11]
I started with 0.3.x and had issue with 1.x.x and 2.x.x

I think the readme or release notes should reflect breaking changes as people might have sensitive data encrypted using this module. If someone forgot to note their version, could lose data

**Comment by goloroden** [comment]
Yes, this is true. We assumed that a change in the major version number would be enough, but you are right: This only points out *that* something has changed with a breaking change, but not *what*. We will keep this in mind for future versions 👍
