### ISSUE TITLE
Error: Key format must be specified

### ISSUE THREAD

**Issue by moda20** [thenativeweb/crypto2#7]
hey i am running this code in my nodejs sever and got the following error 
`Error: Key format must be specified`. It comes from Nodersa, not being able to determine the format of the key  or as i think so. 
```
const crypto2 = require('crypto2');
var privateKey ; crypto2.readPrivateKey(process.env.KEYS_DIR+'/private.pem').then(
  data=>{
    privateKey=data
    console.log("rrrrrrr")
  }
);
```

am i doing something wrong ?

**Comment by goloroden** [comment]
Can you provide a (sample) key to reproduce the error?

PLEASE DO NOT SHARE YOUR ACTUAL PRIVATE KEY!

**Comment by goloroden** [comment]
Thanks 😊

Just to be able to better understand your situation: How did you create this key?

**Comment by goloroden** [comment]
PS: I guess the passphrase is the problem. Haven’t tried it yet, as I’m on the road, but I think using a key without a passphrase should do the trick.

**Comment by moda20** [comment]
I can't set a key without a passphrase, i generated the key using openssl exactly like this : 
openssl genrsa -des3 -out private.pem 2048`

**Comment by goloroden** [comment]
By

> "I can't set a key without a passphrase"

do you mean you can't do it for technical reasons (because OpenSSL doesn't let you), or because you actually *need* a key with a passphrase?

**Comment by goloroden** [comment]
AFAICS node-rsa [does not support keys protected with a passphrase](https://github.com/rzcoder/node-rsa/issues/98)  😕

So, unfortunately, there is nothing I can do about that right now, except replacing node-rsa by something else. We don't currently have the time to do that, but if you want to come up with a PR, we would be very happy to merge it 👍
